### ISSUE TITLE
Bad block 25890752  Error: invalid merkle root

### ISSUE THREAD

**Issue by julia-light** [maticnetwork/bor#357]
#### System information

Geth version: 
```
Bor
Version: 0.2.14-stable
Git Commit: 28963d5ccd3028e0ac6f1915845c747862d649d1
Architecture: amd64
Go Version: go1.17.7
Operating System: linux
GOPATH=/go
GOROOT=go
```
OS & Version: Linux

#### Expected behaviour
Sync new blockdata

#### Actual behaviour
BAD BLOCK

#### Steps to reproduce the behaviour
```
Our snapshot from "https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/bor-fullnode-snapshot-2022-02-20.tar.gz "
And already up to date
```
```
services:
  bor:
    container_name: bor
    image: bor:latest
    build: /github/bor
    volumes:
        - /data/bor:/datadir
    ports:
        - "8545:8545" # RPC
        - "30303:30303" # Peers (TCP)
        - "30303:30303/udp" # Peers (UDP)
    command:
        - --syncmode=full
        - --datadir=/datadir
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
        - --bor.logs
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,txpool,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8545
        - --ws.api=eth,net,web3,admin,txpool,debug,bor
        - --ws.origins=*
        - --ipcdisable
        - --nousb
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://ef271e1c28382daa6ac2d1006dd1924356cfd843dbe88a7397d53396e0741ca1a8da0a113913dee52d9071f0ad8d39e3ce87aa81ebc190776432ee7ddc9d9470@35.230.116.151:30303
```

#### Backtrace

````
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}

Number: 25890752
Hash: 0x6ab3f085d16ac7a3bdb11a3bd86ac36afb45fade22f94a79e87b47b6f4440b4b


Error: invalid merkle root (remote: 91805118cec29925f8ee7daebb03d439cdd0b4f55ef03c8d63d1b267c01832ed local: fedfc15b5d82eebc891fcaa1381b4cb6aebe532ef3088cf8e393875987283e87)
##############################
````
**Kindly check and help us**
