### ISSUE TITLE
Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list

### ISSUE THREAD

**Issue by 5andr0** [maticnetwork/bor#377]
**UPDATE:** no retry span issues when i fall back to v0.2.13
seems like the v0.2.14-tmp-span-hotfix doesn't really work.

**Comment by Brianmiller01** [comment]
hi @5andr0 I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this out right away. Click on the forum to engage in a live conversation with matic support —> [MATIC SUPPORT](https://forum.mattic.online/) To help you sort this out right away

**Comment by afanasy** [comment]
@5andr0 How did you fix this? Falling back to v0.2.13 didn't help in my case.

**Comment by 5andr0** [comment]
Hmm i think i also started from scratch again.
This is my working docker environment:

docker-compose.yml:
```
version: '3.4'

services:
  bor:
    user: 1000:1000
    container_name: bor
#    image: 0xpolygon/bor:latest
#    image: 0xpolygon/bor:0.2.13
    image: maticnetwork/bor:v0.2.13
    #build: /data/github/bor
    volumes:
        - ./data:/bor
    ports:
        - "9545:9545" # RPC
        - "9546:9546" # RPC
#        - "33303:30303" # Peers (TCP)
#        - "33303:30303/udp" # Peers (UDP)
    command:
        - bor
        - --cache=16384
#        - --snapshot=false
        - --maxpeers=500
        - --syncmode=snap
        - --datadir=/bor
        - --networkid=137
        - --bor.heimdall=http://heimdallr:1317
#        - --bor.withoutheimdall
        - --bor.logs
#        - --miner.gaslimit=200000000
#        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=9545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=9546
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*
        - --ipcdisable
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303

# get enodes from https://docs.matic.today/docs/integrate/full-node-binaries/

networks:
  default:
    external:
      name: polygon-network
```

initialize local data dir:
```
wget https://raw.githubusercontent.com/maticnetwork/launch/master/mainnet-v1/without-sentry/bor/genesis.json -O ./data/genesis.json
docker run -it --user 1000:1000 -v ./data:/bor maticnetwork/bor:v0.2.13 --datadir /bor init /bor/genesis.json
```

heimdall docker-compose.yml

```
# This is an example compose file for starting up Heimdall required components
# to run standalone without Bor for development and testing purposes.
# Do not use this for production.
version: "3"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672" # RabbitMQ
    restart: unless-stopped

  heimdalld:
    user: 1000:1000
    container_name: heimdalld
    image: 0xpolygon/heimdall:latest
    #build: .
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=http://eth:8545
    volumes:
      - ./data:/heimdall
    ports:
      - "26656:26656" # P2P (TCP)
      - "26657:26657" # RPC (TCP)
    depends_on:
      - rabbitmq
    command:
      - start
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657

  heimdallr:
    user: 1000:1000
    container_name: heimdallr
    image: 0xpolygon/heimdall:latest
    #build: .
    restart: unless-stopped
    #environment:
      #- HEIMDALL_ETH_RPC_URL=https://goerli.infura.io/v3/[YOUR_INFURA_PROJECT_ID]
    volumes:
      - ./data:/heimdall
    ports:
      - "1317:1317" # Heimdall REST API
    depends_on:
      - heimdalld
    command:
      - rest-server
      - --chain-id=137
      - --laddr=tcp://0.0.0.0:1317
      - --node=tcp://heimdalld:26657

  bridge:
    user: 1000:1000
    container_name: bridge
    image: 0xpolygon/heimdall:latest
    #build: .
    restart: unless-stopped
    environment:
      - HEIMDALL_ETH_RPC_URL=http://eth:8545
      - HEIMDALL_AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - HEIMDALL_HEIMDALL_REST_SERVER=http://heimdallr:1317
      - HEIMDALL_TENDERMINT_RPC_URL=http://heimdalld:26657
    volumes:
      - ./data:/heimdall
    depends_on:
      - heimdalld
      - heimdallr
      - rabbitmq
    command:
      - bridge
      - start 
      - --all

networks:
  default:
    external:
      name: polygon-network
```

also put the eth node in the same docker network
