### ISSUE TITLE
[bor 0.2.16 mainnet] bor consumes extremely high loading when using web sockets

### ISSUE THREAD

**Issue by manbobo2002** [maticnetwork/bor#471]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://docs.polygon.technology/docs/faq/technical-faqs) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: [e.g. v0.2.16] 
0.2.16-stable

Heimdall client version: [e.g. v0.2.10] 
0.2.10

OS & Version: Windows / Linux / OSX
Debian 10

Environment: Polygon Mainnet / Polygon Mumbai / Devnet
Polygon Mainnet

Type of node: Validator / Sentry / Archive
Archive

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

#### **Reproduction Steps**

Please mention the steps required to reproduce this issue. 

#### **Logs / Traces / Output / Error Messages**
 ![image](https://user-images.githubusercontent.com/25196415/181148191-1f8a566a-d02b-414d-b192-24ec13a7af31.png)

![image](https://user-images.githubusercontent.com/25196415/181148334-bcd91965-42ce-45ef-a9f4-90c9956b617e.png)

Config for bor:
```
# {{ ansible_managed }}
version: '3.4'

services:
  bor:
    container_name: bor
    image: maticnetwork/bor:v{{ bor_version }}
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    volumes:
        - "{{ bor_data_dir }}:/datadir"
    ports:
        - "8545:8545" # RPC
        - "8546:8546" # WS
        - "30303:30303" # Peers (TCP)
        - "30303:30303/udp" # Peers (UDP)
    command:
        - bor
        - --syncmode=full
        - --datadir=/datadir
{% if (heimdall_network == "mainnet") %}
        - --networkid=137
{% else %}
        - --networkid=80001
{% endif %}
        - --bor.heimdall=http://heimdallr:1317
        - --bor.logs
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8546
        - --gcmode=archive
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*
        - --ipcdisable
        - --nousb
        - --config=/datadir/bor/bor_config.toml
{% if (heimdall_network == "mainnet") %}
        - --bootnodes=enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
{% else %}
        - --bootnodes=enode://095c4465fe509bd7107bbf421aea0d3ad4d4bfc3ff8f9fdc86f4f950892ae3bbc3e5c715343c4cf60c1c06e088e621d6f1b43ab9130ae56c2cacfd356a284ee4@18.213.200.99:30303,enode://90676138b9823f4b834dd4fb2f95da9f54730a74ff9deb4782c4be98232f1797806a62375d9b6d305af49f7c0be69a9adcad7eb533091bd15b77dd5997b256e2@54.227.107.44:30303,enode://0a9dded21b1b332376a3a255d2aaf1b4a5d279d99a71be9dd3c7328d3ebdd2986840016eef614fba57b719380e92e6a2b79b640e55e651dab48f36770eea1926@54.147.31.250:30303
{% endif %}
networks:
  default:
    external:
      name: polygon
```

I am using AWS instance c5a.12xlarge

How can I deal with this issue?
