### ISSUE TITLE
Bor always hit 'invalid merkle root' error when starting from snapshot

### ISSUE THREAD

**Issue by yhvicey** [maticnetwork/bor#798]
#### **System information**

Bor client version: 0.3.6-stable
Heimdall client version: 0.3.0
OS & Version: Alpine Linux 3.14.8
Environment: Polygon Mainnet
Type of node: Full
Additional Information: N/A

#### **Overview of the problem**

When starting bor full node following [official guide](https://wiki.polygon.technology/docs/operate/snapshot-instructions-heimdall-bor) and [latest snapshots](https://snapshots.polygon.technology/), bor node will always hit 'Error: invalid merkle root' error after syncing for a while.
Expected behavior: Bor node should be able to sync all the way until latest block

#### **Reproduction Steps**

We're running bor & heimdall nodes on k8s and they're at different pods but same namespace. Services are configured and are reachable.

Bor checkpoint extraction command: `tar -I zstd -xvf /polygon/bor/checkpoint -C /polygon/bor/bor/chaindata`
Bor command: `/usr/bin/bor server -config=/polygon/bor/config.toml`
Heimdall checkpoint extraction command: `tar -I zstd -xvf /polygon/heimdall/checkpoint -C /polygon/heimdall/data/`
Heimdall command: `/usr/bin/heimdalld start --home /polygon/heimdall --rest-server`

bor/config.toml:
```toml
datadir = "/polygon/bor"
[heimdall]
  url = "http://heimdall:1317"
[jsonrpc]
  [jsonrpc.http]
    enabled = true
    host = "0.0.0.0"
    api = ["eth", "net", "web3", "txpool", "bor", "debug"]
    vhosts = ["*"]
    corsdomain = ["*"]
```

heimdall/heimdall-config.toml:
```toml
eth_rpc_url = "some-eth-node-addr"
bor_rpc_url = "http://bor:8545"
```

#### **Logs / Traces / Output / Error Messages**
 
```log
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}

Number: 40324816
Hash: 0x8b314fab0744c736d38d3a584bcb76a1698600cdca9aea2e60fbd6f5096435b8
(Omitted lots of stuffs here)
Error: invalid merkle root (remote: 0625023dd3fa31e1581f1c8aedaac52bbb039f0c7a64ef47fd68989806ea35ba local: 958ee4587e6c74ee36e3910235b23b9cfb8a3a1b94c94166eb7c5fbc98a67874)
##############################
```

**Additional Information**

Please refer to above section for detailed setup/configuration and let me know if any additional info needed.

We've also tried below repair actions mentioned in [Known Issues](https://wiki.polygon.technology/docs/maintain/validate/kb/known-issues/#1-error-bad-blockinvalid-merkle):

- Restart bor/heimdall
- Rewind node to previous blocks

But none of above actions work.
